### ISSUE TITLE
[Bug] Plugin crashes on FileTrees

### ISSUE THREAD

**Issue by lisachenko** [goaop/idea-plugin#18]
There is strange exception in plugin with `FileTrees`, probably this can be related to latest changes. @artspb maybe you have an idea what's wrong here?

```
FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=true}; roots=[HtmlFile:class-woven.php, PHP file]; root trees=[FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=true}, FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=false}]
java.lang.RuntimeException: FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=true}; roots=[HtmlFile:class-woven.php, PHP file]; root trees=[FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=true}, FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=false}]
	at com.intellij.psi.impl.source.FileTrees.withExclusiveStub(FileTrees.java:74)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:719)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:73)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:53)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:331)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:617)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:605)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:62)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:360)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:312)
	at com.aopphp.go.pointcut.PointcutAdvisor.getMatchedElements(PointcutAdvisor.java:95)
	at com.aopphp.go.line.marker.AdvisorLineMarkerProvider.collectNavigationMarkers(AdvisorLineMarkerProvider.java:53)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:49)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:40)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:212)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by lisachenko** [comment]
```
2018-01-07 20:33:14,939 [1299582295]  ERROR - ht.daemon.impl.LineMarkersPass - PhpStorm 2017.2.4  Build #PS-172.4155.41 
2018-01-07 20:33:14,939 [1299582295]  ERROR - ht.daemon.impl.LineMarkersPass - JDK: 1.8.0_152-release 
2018-01-07 20:33:14,939 [1299582295]  ERROR - ht.daemon.impl.LineMarkersPass - VM: OpenJDK 64-Bit Server VM 
2018-01-07 20:33:14,940 [1299582296]  ERROR - ht.daemon.impl.LineMarkersPass - Vendor: JetBrains s.r.o 
2018-01-07 20:33:14,940 [1299582296]  ERROR - ht.daemon.impl.LineMarkersPass - OS: Mac OS X 
2018-01-07 20:33:14,940 [1299582296]  ERROR - ht.daemon.impl.LineMarkersPass - Last Action: GotoClass 
2018-01-07 20:33:20,781 [1299588137]  ERROR - ht.daemon.impl.LineMarkersPass - FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=true}; roots=[HtmlFile:class-woven.php, PHP file]; root trees=[FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=true}, FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=false}] 
java.lang.RuntimeException: FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=true}; roots=[HtmlFile:class-woven.php, PHP file]; root trees=[FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=true}, FileTrees{stub=null, AST=null, astLoaded=true, useStrongRefs=false}]
```

**Comment by artspb** [comment]
What's `FileTrees`?

**Update.** Oh, that's ours `FileTrees`. I'll take a look.

**Comment by artspb** [comment]
What's version? AFAIK it should be already fixed.

**Comment by lisachenko** [comment]
Version is following:

> PhpStorm 2017.2.4  Build #PS-172.4155.41 
JDK: 1.8.0_152-release
VM: OpenJDK 64-Bit Server VM

**Comment by lisachenko** [comment]
I will try now with the latest version of PhpStorm

**Comment by lisachenko** [comment]
Issue was fixed after cache invalidation and restart. Looks like temporary glitch...

Anyway, thanks for looking into this issue!
